"""Añadir relaciones de Sede a User y Reservation

Revision ID: 744ecce7aaf8
Revises: 
Create Date: 2025-11-15 14:07:11.057457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744ecce7aaf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sede_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_reservation_sede_id'), ['sede_id'], unique=False)
        batch_op.create_foreign_key(None, 'sede', ['sede_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sede_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sede', ['sede_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sede_id')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reservation_sede_id'))
        batch_op.drop_column('sede_id')

    # ### end Alembic commands ###
